apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    deployment: backend
  namespace: dicoding-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/hdkef/karsajobs:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 20m
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: "mongo"
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD