apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
  namespace: dicoding-ns
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: backend
  type: NodePort