apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    deployment: frontend
  namespace: dicoding-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/hdkef/karsajobs-ui:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 20m
        env:
          - name: VUE_APP_BACKEND
            value: "http://{{ .Values.nodeIP }}:30007"