apiVersion: v1
kind: Service
metadata:
  labels:
    nodeport: frontend
  name: frontend-public
  namespace: dicoding-ns
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30006
  selector:
    app: frontend
  type: NodePort